version: "3"
services:
  api:
    image: express-api
    build:
      context: .
      dockerfile: dockerFileExpress
    ports:
      - "3000:3000"
  angular:
    image: angular-app
    build:
      context: .
      dockerfile: dockerFileAngular
    ports:
      - "4200:4200"
